# Generated by Django 5.2.5 on 2025-09-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(db_column='T001idpersona', editable=False, primary_key=True, serialize=False)),
                ('apellido', models.CharField(db_column='T001Apellido', max_length=100)),
                ('nombre', models.CharField(db_column='T001Nombre', max_length=100, unique=True)),
                ('documento', models.CharField(db_column='TeelDocumento', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.AutoField(db_column='T002IdTarea', editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
