# Generated by Django 5.2.5 on 2025-09-03 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'persona', 'verbose_name_plural': 'personas'},
        ),
        migrations.AlterModelOptions(
            name='tarea',
            options={'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.AddField(
            model_name='persona',
            name='activo',
            field=models.BooleanField(db_column='T001Activo', default=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_limite',
            field=models.DateField(blank=True, db_column='T002FechaLimite', null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='persona',
            field=models.ForeignKey(blank=True, db_column='T002PersonaId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='api_app.persona'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='titulo',
            field=models.CharField(db_column='T002Titulo', default='Sin título', max_length=200),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(db_column='T001Apellido', default='ApellidoDesconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='documento',
            field=models.CharField(db_column='T001Documento', default='0000000000', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(db_column='T001Nombre', default='NombreDesconocido', max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='persona',
            table='T001Persona',
        ),
        migrations.AlterModelTable(
            name='tarea',
            table='T002Tarea',
        ),
    ]
