# Generated by Django 5.2.5 on 2025-09-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_alter_persona_options_alter_tarea_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cédula de extranjería'), ('PP', 'Pasaporte')], db_column='T001TipoDocumento', default='CC', max_length=2),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(db_column='T001Nombre', default='NombreDesconocido', max_length=100),
        ),
    ]
